apiVersion: v1
kind: Pod

metadata:
  name: salary_hike_predictor

spec:
  containers: salary_hike_predictor
  - name: kaja184/salary-hike-predictor:latest
    image: nginx:1.14.2
    ports:
    - containerPort: 80
